### ISSUE TITLE
Need Wix 3 to run jpackage task

### ISSUE THREAD

**Issue by theroman18** [mjparme/javafx-template#2]
Could you add to the readme that wix version 3 is required to run jpackage? Also Wix version 4 doesn't work with jpackage

**Comment by mjparme** [comment]
What is wix? I have never heard of it and have never needed it to build my JavaFX apps using this template.

**Comment by mjparme** [comment]
Are you referring to this? https://wixtoolset.org

**Comment by theroman18** [comment]
Yes that is the software.

This error was thrown when I tried running the jpackage task from Gradle using intellij 2023:

WARNING: Using incubator modules: jdk.incubator.jpackage

Can not find WiX tools (light.exe, candle.exe) Download WiX 3.0 or later from https://wixtoolset.org/ and add it to the PATH. Error: Invalid or unsupported type: [null]


This stackoverflow solution helped:

https://stackoverflow.com/a/66930661

**Comment by mjparme** [comment]
I think mentioning WIX in the README would just confuse people into thinking it is something they need. I had never heard of it until this issue was opened.
