### ISSUE TITLE
Intellij: error: cannot access module-info

### ISSUE THREAD

**Issue by johnsie** [mjparme/javafx-template#3]
In Intellij I opened the project and let gradle do its thing. Then when I tried to run the MyApplication  class as described in readme I got the error message:

error: cannot access module-info

**Comment by mjparme** [comment]
I just tested it out again to make sure I didn't break something and all was well. I cloned it, opened IntellliJ, and went to File -> Open and selected the directory that was created when I cloned it. IntelliJ was ready in about a minute, then I hit the green arrow next to the `MyApplication` class name, and chose run. It fired up fine.

Did you maybe choose the wrong directory with File -> Open? If you execute: `git clone https://github.com/mjparme/javafx-template.git` it will clone to a directory called `javafx-template`. That is the directory you need to choose (alternatively you can choose the `build.gradle` file in that directory)

**Comment by mjparme** [comment]
As another troubleshooting step, go to the command-line and execute `./gradlew run`, does it start?

(if you are on windows you probably need to do `gradlew.bat run`)

**Comment by mjparme** [comment]
Closed due to lack of response.
